name: Fetch recent blog posts
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-recent-blog-posts:
    name: Fetch recent blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run script
        run: deno task build
      - name: Git setup
        run: git config --global user.email readme-bot@example.com && git config --global user.name readme-bot
      - name: Git commit README.md file
        run: git diff --quiet && git diff --staged --quiet || git commit -am "update readme (bot)" && git push
